import json
from dataclasses import dataclass, fields, is_dataclass
from pathlib import Path
from typing import Any, TypeVar

from makefile_generator.config import CACHED_CONFIG_FILE, MKCACHE
from makefile_generator.core.loader import ProjectConfig

from .exceptions import ExpectedUserError
from .model import Project


@dataclass(frozen=True, kw_only=True, slots=True)
class _CachedTarget:
    paths: list[Path]
    mtimes: list[int]
    
    def __iter__(self):
        targets = zip(self.paths, self.mtimes)
        
        for path, mtime in targets:
            yield path, mtime
    
@dataclass(frozen=True, kw_only=True, slots=True)
class CachedModules(_CachedTarget):
    pass

@dataclass(frozen=True, kw_only=True, slots=True)
class CachedPublics(_CachedTarget):
    pass

@dataclass(frozen=True, kw_only=True, slots=True)
class MkCache:
    config: ProjectConfig
    modules: CachedModules
    publics: CachedPublics
    tests: list[Path]
    root: Path

T = TypeVar('T')

def _make_dataclass_from_dict(
    cls: type[T], 
    data: dict[str, Any]
    ) -> T:
    
    if not is_dataclass(cls):
        raise ExpectedUserError(f'{cls!r} is not a dataclass!')
    
    kwargs = {}
    
    for field in fields(cls):
        value = data.get(field.name)
        
        if is_dataclass(field.type) and isinstance(value, dict):
            value = _make_dataclass_from_dict(field.type, value) #pyright: ignore[reportArgumentType]   
    
        kwargs[field.name] = value
        
    return cls(**kwargs)

def generate_mkcache(project: Project) -> None:
    text_list: list[str] = []
    text_list.append('''\
===================================================================   
        Auto-generated by MKGEN. Do not edit manually.
===================================================================       
''')
    text_list.append('PATHS\n')
    build_dir = Path(project.build_dir)

    for module in project.modules:
        text_list.append(f'{module.path} | {module.path.stat().st_mtime_ns} | module\n')

    for test in project.tests:
        text_list.append(f'{test.path} | {test.path.stat().st_mtime_ns} | test\n')

    for public in project.publics:
        text_list.append(f'{public} | {public.stat().st_mtime_ns} | public\n')
        
    text_list.append('ROOT DIR\n')
    text_list.append(f'{project.root_dir}\n')
    
    text_list.append('CONFIGS\n')

    cached_config_path = build_dir / CACHED_CONFIG_FILE
    text_list.append(f'Cached config path: {cached_config_path}\n')
    
    data: str = ''.join(text_list)

    cache = build_dir / MKCACHE
    cache.write_text(data)
    json.dump(
        project.config_asdict,
        cached_config_path.open(mode='w', encoding='utf-8'),
        indent=4
    )
    
def parse_mkcache(build_dir: Path) -> MkCache | None:
    mod_paths: list[Path] = []
    tests: list[Path] = []
    pub_paths: list[Path] = []
    
    pub_mtimes: list[int] = []
    mod_mtimes: list[int] = []
    
    config_path = build_dir / CACHED_CONFIG_FILE
    cache = build_dir / MKCACHE
    root = Path.cwd() #!This is being done solely to satisfy Pylance since root will ALWAYS be overwitten during cache parsing, and i say ALWAYS

    if not cache.exists():
        return None

    #?I'm starting at index 3 to discard the auto-generated text
    current = ''
    for line in cache.read_text().splitlines()[3:]:
        line = line.strip()

        if not line:
            continue

        if line == 'PATHS':
            current = 'paths'
        elif line == 'ROOT DIR':
            current = 'root_dir'
        elif line == 'CONFIGS':
            current = 'config'
        else:
            if current == 'paths':
                if '|' not in line:
                    continue

                path, mtime, type = [s.strip() for s in line.split('|', maxsplit=2)]
                path=Path(path)

                if not path.exists():
                    continue

                match type:
                    case 'module':
                        mod_paths.append(path)
                        mod_mtimes.append(int(mtime))
                    case 'test':
                        tests.append(path)
                    case 'public':
                        pub_paths.append(path)
                        pub_mtimes.append(int(mtime))
            elif current == 'root_dir':
                root = Path(line.strip())
            elif current == 'config':
                continue
            else:
                raise ValueError(f'Line outside section: {line}') #TODO: handle differently
            
    data = json.load(config_path.open())
    config = _make_dataclass_from_dict(ProjectConfig, data)

    return MkCache(
        config=config,
        modules=CachedModules(paths=mod_paths, mtimes=mod_mtimes),
        publics=CachedPublics(paths=pub_paths, mtimes=pub_mtimes),
        tests=tests,
        root=root
    )