from .constants import (C_COMPILERS, C_STANDARDS, CPP_COMPILERS, CPP_STANDARDS,
                        RAYLIB_CFLAGS, RAYLIB_FLAGS, SDL2_CFLAGS, SDL2_FLAGS,
                        SFML_CFLAGS, SFML_FLAGS, TEMPLATES, TEMPLATES_DIR,
                        WIN32_RESERVED_NAMES)

__all__ = [
    'SDL2_CFLAGS',
    'SDL2_FLAGS',
    'SFML_CFLAGS',
    'SFML_FLAGS',
    'RAYLIB_CFLAGS',
    'RAYLIB_FLAGS',
    'CPP_STANDARDS',
    'C_STANDARDS',
    'CPP_COMPILERS',
    'C_COMPILERS',
    'TEMPLATES_DIR',
    'TEMPLATES',
    'WIN32_RESERVED_NAMES'
]
